[project]
name = "contextual-greetings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.6.0",
    "starlette>=0.46.1",
    "uvicorn>=0.34.0",
]
