[project]
name = "mcp-simple-sse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "click>=8.1.8",
    "httpx>=0.28.1",
    "mcp>=1.6.0",
]
